### ISSUE TITLE
error when tried CreateNonRedundantHybrids

### ISSUE THREAD

**Issue by haowenz** [luslab/hiclipr#1]
Hi,

I run the following command and got error message. Does anyone know why?

```
nonredundant.hybrids <- CreateNonRedundantHybrids(islands,nonislands)
Error in setnames(islands, "islandid", "id") : 
  Items of 'old' not found in column names: islandid
```

Thanks,
Howen

**Comment by amchakra** [comment]
This function just merges the output of the functions `FindIslands` and `FindNonIslandHybrids`. 

The error is because the data table being passed as `islands` has not had the islands assigned island ids. Could you check if your output from `FindIslands` has `islandid` as a column name please?

**Comment by haowenz** [comment]
I tried again and it works now.

Thanks.
